source:         ./source
destination:    ./public
permalink:      /:categories/:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "articles/creating-a-game-with-javascript" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "article-game-dev.html"
